{{- if and (not .Values.existingSecret) (not .Values.vault.enabled) }}
{{- $secretName := printf "%s-auth" (include "pinard-nats.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "pinard-nats.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  sys-password: {{ if $existingSecret }}{{ index $existingSecret.data "sys-password" | b64dec }}{{ else }}{{ .Values.sysPassword | default (randAlphaNum 24) }}{{ end }}
  {{- range .Values.accounts }}
  {{ .name }}-password: {{ if $existingSecret }}{{ index $existingSecret.data (printf "%s-password" .name) | b64dec | default (randAlphaNum 24) }}{{ else }}{{ .password | default (randAlphaNum 24) }}{{ end }}
  {{- end }}
{{- end }}
