apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinard-nats.fullname" . }}
  labels:
    {{- include "pinard-nats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
    - port: 6222
      targetPort: cluster
      protocol: TCP
      name: cluster
    - port: {{ .Values.service.monitorPort }}
      targetPort: monitor
      protocol: TCP
      name: monitor
    {{- if .Values.websocket.enabled }}
    - port: {{ .Values.websocket.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
    {{- end }}
  selector:
    {{- include "pinard-nats.selectorLabels" . | nindent 4 }}
